-- Create table
create table COBERT_PLAN_PRERENOV
(
  CODINTER    VARCHAR2(20),
  IDEPOL      NUMBER,
  CODPROD     VARCHAR2(20),
  CODPLAN     VARCHAR2(20),
  REVPLAN     VARCHAR2(20),
  CODCOBERT   VARCHAR2(20),
  DESCOBERT   VARCHAR2(1000),
  SUMAASEG    NUMBER,
  PRIMACOBERT NUMBER
);