-- Create table
create table USUARIO_PORTAL_WEB
(
  TOKEN    VARCHAR2(100),
  NOMINTER VARCHAR2(100),
  STATUS   VARCHAR2(12),
  USERNAME VARCHAR2(12),
  CODUSER  VARCHAR2(12),
  ROLNAME  VARCHAR2(13),
  FECSTS   DATE
);