-- Create table
create table RENOVACION
(
  CODPROD  VARCHAR2(4),
  DESCPROD VARCHAR2(20),
  NUMPOL   VARCHAR2(20),
  TOMADOR  VARCHAR2(100),
  CODINTER VARCHAR2(4),
  OFICINA  VARCHAR2(100),
  IDEPOL   NUMBER,
  CODOFI   VARCHAR2(4)
);