-- Create table
create table ASEGURADOS_PRE_RENOVACION
(
  NOMBRE   VARCHAR2(300),
  DESCPROD VARCHAR2(300),
  NUMPOL   VARCHAR2(20),
  FECINI   DATE,
  FECFIN   DATE,
  IDEPOL   NUMBER,
  CODINTER NUMBER
);