-- Create table
create table PLANES_ASEGURADOS_PRERENOV
(
  CODINTER    VARCHAR2(20),
  IDEPOL      NUMBER,
  DESCPLAN    VARCHAR2(300),
  CODPLAN     VARCHAR2(20),
  REVPLAN     VARCHAR2(20),
  PRIMA       NUMBER,
  CODPROD     VARCHAR2(20),
  MCAPRENENOV VARCHAR2(1)
);